using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace FilePickerTest.Cryptography.Test
{
    [TestClass]
    public class BlowfishStreamTest
    {
        [TestMethod]
        public void FlushTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void ReadTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void WriteTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void BeginReadTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void EndReadTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void BeginWriteTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void SeekTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void SetLengthTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}