using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace FilePickerTest.Cryptography.Test
{
    [TestClass]
    public class BlowfishTest
    {
        [TestMethod]
        public void EncipherTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void Encipher1Test()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void DecipherTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void Decipher1Test()
        {
            Assert.Fail("autogenerated");
        }
    }
}